### ISSUE TITLE
unable to open minecraft plz help

### ISSUE THREAD

**Issue by flyingbluesnake** [kreezxil/the-seilican-experience#32]
when i press play it starts to open then crashes half way through giving this crash log 

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/24/20 8:21 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.davenonymous.bonsaitrees2.misc.PotColorizer.init(PotColorizer.java:33) ~[?:2.1.2.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_158_PotColorizer_init_Block.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:itlt:CustomWindowTitle,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[client-1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.48.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at com.davenonymous.bonsaitrees2.misc.PotColorizer.init(PotColorizer.java:33)
	at net.minecraftforge.eventbus.ASMEventHandler_158_PotColorizer_init_Block.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3040125960 bytes (2899 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.48.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.48
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.5.jar Cucumber Library {cucumber@3.0.5 CREATE_REGISTRIES}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 CREATE_REGISTRIES}
		nethercraft-1.15.2-1.0.7.jar Nethercraft {nethercraft@1.0.7 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 CREATE_REGISTRIES}
		terrible_chest-1.15.2-2.jar Terrible Chest {terrible_chest@1.15.2-2 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 CREATE_REGISTRIES}
		FallingTree-1.15.2-2.1.0+24.jar Falling Tree {falling_tree@2.1.0+24 CREATE_REGISTRIES}
		ChineseWorkshop-1.15.2-2.4.3.jar ChineseWorkshop {chineseworkshop@2.4.3 CREATE_REGISTRIES}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 CREATE_REGISTRIES}
		noautojump-1.15.2-1.jar No Auto-Jump {noautojump@1.15.2-1 CREATE_REGISTRIES}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 CREATE_REGISTRIES}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 CREATE_REGISTRIES}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		Powah-1.15.2-1.1.12.jar Powah {powah@1.1.12 CREATE_REGISTRIES}
		VanillaTweaks-1.15.2.1.5.22.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.22 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 CREATE_REGISTRIES}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 CREATE_REGISTRIES}
		walljump-forge-1.15.2-1.3.5.jar Wall-Jump! {walljump@1.15.2-1.3.5 CREATE_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 CREATE_REGISTRIES}
		SnowRealMagic-1.15.2-1.8.0.jar Snow! Real Magic! {snowrealmagic@1.8.0 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 CREATE_REGISTRIES}
		forge-1.15.2-31.1.48-universal.jar Forge {forge@31.1.48 CREATE_REGISTRIES}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 CREATE_REGISTRIES}
		exp_bottling-1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 CREATE_REGISTRIES}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.2.jar Mystical Agriculture {mysticalagriculture@3.0.2 CREATE_REGISTRIES}
		forge-1.15.2-31.1.48-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		itlt-1.15.2-1.0.2.jar It's the little things {itlt@1.15.2-1.0.2 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.355-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.354 CREATE_REGISTRIES}
		Lollipop-1.15.2-1.0.14.jar Lollipop {lollipop@1.0.14 CREATE_REGISTRIES}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version CREATE_REGISTRIES}
		simplybackpacks-1.15.2-1.4.5.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.5 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 CREATE_REGISTRIES}
		Xaeros_Minimap_20.7.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.7.1 CREATE_REGISTRIES}
		morecharcoal-1.15.2-1.jar More Charcoal {morecharcoal@1.15.2-1 CREATE_REGISTRIES}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 CREATE_REGISTRIES}
		f2l-0.3.1.jar Flesh 2 Leather {f2l@0.3.1 CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 CREATE_REGISTRIES}
		structurize-0.10.305-ALPHA.jar Structurize {structurize@0.10.305-ALPHA CREATE_REGISTRIES}
		fancymenu_1.0.beta_MC_1.15-1.15.2.jar §dFancy§5Menu {fancymenu@1.0 ERROR}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 CREATE_REGISTRIES}
		minecolonies-0.11.872-ALPHA-universal.jar Minecolonies {minecolonies@0.11.872-ALPHA CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 CREATE_REGISTRIES}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 CREATE_REGISTRIES}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal CREATE_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		CHAS v1.3 for 1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 CREATE_REGISTRIES}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 CREATE_REGISTRIES}
		Ma-Essentials-1.15.2-3.0.3.jar Ma Essentials {ma-essentials@1.15.2-3.0.3 CREATE_REGISTRIES}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 CREATE_REGISTRIES}
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon R9 M370X OpenGL Engine GL version 2.1 ATI-2.11.20, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz

**Comment by flyingbluesnake** [comment]
and yes i am up to date for the mod pack

**Comment by kreezxil** [comment]
in the future you and your friend if you have the same issue post in the same ticket please.

**Comment by kreezxil** [comment]
I need to know which launcher are you using? Twitch or GD Launcher? if not Twitch please try it in https://gdevs.io

**Comment by flyingbluesnake** [comment]
I'm using ATlauncher on mac i haven't been able to get GD launcher to work because it says i need java dev kit and i can't find the download and i can't do twitch because it can't use the minecraft native launcher on mac

**Comment by flyingbluesnake** [comment]
i finally was able to get gd launcher working but i crashed again for what it seems to be a different reason   
https://pastebin.com/ZNp3LHRu

**Comment by kreezxil** [comment]
@flyingbluesnake use these dev builds, they will download the correct dev kit for you for itself and not modify the one you have for your overall system, the same way that twitch does it. https://github.com/gorilla-devs/GDLauncher/actions/runs/80966313

**Comment by kreezxil** [comment]
that last report is complaining about your java.

also attatch the latest.log in logs/ as well as crah reports from now on. as they contain more data to analyze. you might have to use https://gist.github.com as they tend to be too large for most other pasting services.

**Comment by flyingbluesnake** [comment]
the dev build of gdlauncher has been doing the automatic setup at 99% for the past hour idk how to get it to finish

**Comment by kreezxil** [comment]
so i dusted off an old mac from closet that is running OSX EL CAPITAN, a 4GB SYSTEM with the following specs

```
  Model Name:	iMac
  Model Identifier:	iMac11,2
  Processor Name:	Intel Core i3
  Processor Speed:	3.06 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	4 GB
  Processor Interconnect Speed:	5.86 GT/s
```

And I didn't have a problem with the default GD LAUNCHER from https://gdevs.io

I also allocated 3.8GB of ram.

In regards to the 99% issue please join the GD LAUNCHER discord channel and let them know, they are better suited to trouble shooting that.

**Comment by flyingbluesnake** [comment]
can you please send me a version of the modpack without the start animation?
my friend said there was a new start thing and i think thats whats breaking my stuff.

**Comment by flyingbluesnake** [comment]
i have been able to get another mod pack working but still can't get the seilican experience to work

**Comment by kreezxil** [comment]
This is really funny because I have a 4gb i3 iMac that I tested it against.
Did you add other mods to the pack?

**Comment by flyingbluesnake** [comment]
i haven't added or removed any mod from the pack

**Comment by kreezxil** [comment]
Are you using GDLauncher like I suggested? I used GDLauncher for my test.

**Comment by flyingbluesnake** [comment]
yes i used the gdlauncher

**Comment by kreezxil** [comment]
As much as it irks me, now try it Twitch launcher. make sure you are
grabbing the latest update too.

**Comment by flyingbluesnake** [comment]
Twitch launcher doesn't work for minecraft version 1.11 onward with mac

**Comment by kreezxil** [comment]
wowzers, I just test that first hand on mac, it's amazing to me or not actually that Twitch has abandoned the Minecraft Mac Community.

**Comment by kreezxil** [comment]
@flyingbluesnake Looks like I'm gonna need you to explain your crashes better.

Installed GDLAUNCHER on my Mac.
Installed Java 8 LTS w/ HOTSPOT from https://adoptopenjdk.net
Installed The Seilican Experience
Launched it
Joined the world

No problems

I feel like you either need to remove java and gdl and install both of those fresh again

or

you're failing to tell me that you are actually connecting to the server or single player world and are crashing out of it. And that issue might be related to something you crafted.

In this particular instance I'm leaning towards bonsai plants.

need to know for sure.

**Comment by flyingbluesnake** [comment]
i wasn't able to open the mod pack at all i don't know what made this problem but I factory reset my computer and redownloaded everything and i can now join using GDLAUNCHER
